global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gemeo-api'
    static_configs:
      - targets: ['api:5000']
    scrape_interval: 10s

  - job_name: 'gemeo-simulator'
    static_configs:
      - targets: ['simulator:5001']
    scrape_interval: 10s

